### ISSUE TITLE
Failed to run Google Analysis Jenkins plugin

### ISSUE THREAD

**Issue by llbit** [google/shipshape#61] opened 2015-07-01 21:24 UTC
I followed the instructions for the Jenkins plugin and failed to run it in jenkins.

Jenkins version: https://github.com/junit-team/junit.git

Console output:

```
Started by user anonymous
Building in workspace /var/jenkins_home/jobs/JUnit/workspace
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/junit-team/junit.git # timeout=10
Fetching upstream changes from https://github.com/junit-team/junit.git
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/junit-team/junit.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision fe1753703f4f20718b3479dd71e01e9e4d96cf1f (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f fe1753703f4f20718b3479dd71e01e9e4d96cf1f
 > git rev-list fe1753703f4f20718b3479dd71e01e9e4d96cf1f # timeout=10
[Shipshape] Verbose mode enabled
[Shipshape] Using workspace path: /var/jenkins_home/jobs/JUnit/workspace
[Shipshape] Using output path: /var/jenkins_home/jobs/JUnit/workspace
[Shipshape] Using categories: ExtendJ
[Shipshape] Using socket: unix:///var/run/docker.sock
[Shipshape] Creating Shipshape request ...
FATAL: com/google/protobuf/ProtocolStringList
java.lang.NoClassDefFoundError: com/google/protobuf/ProtocolStringList
	at com.google.jenkins.plugins.analysis.ShipshapeSlave.constructShipshapeRequest(ShipshapeSlave.java:179)
	at com.google.jenkins.plugins.analysis.ShipshapeSlave.call(ShipshapeSlave.java:154)
	at com.google.jenkins.plugins.analysis.ShipshapeSlave.call(ShipshapeSlave.java:47)
	at hudson.FilePath.act(FilePath.java:1076)
	at com.google.jenkins.plugins.analysis.AnalysisRunner.perform(AnalysisRunner.java:118)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
	at hudson.model.Build$BuildExecution.build(Build.java:203)
	at hudson.model.Build$BuildExecution.doRun(Build.java:160)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:536)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.ProtocolStringList
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1375)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1325)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1078)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
Finished: FAILURE
```

![screenshot from 2015-07-01 14 23 01](https://cloud.githubusercontent.com/assets/2757386/8465187/cbc324f8-1ffc-11e5-8802-4f1e19260e5a.png)

**Comment by emsod** [comment] 2015-07-01 21:49
This is a duplicate of issue #42.

**Closed** 2015-07-01 22:01 UTC
