### ISSUE TITLE
Shipshape exits with "HTTP client did not become healthy"

### ISSUE THREAD

**Issue by mernst** [google/shipshape#35] opened 2015-05-23 06:26 UTC
I followed the simple installation instructions at https://github.com/google/shipshape .

Then, when I ran Shipshape, I got

% shipshape --categories="go vet,JSHint,PyLint" /home/mernst/research/types/checker-framework
E0523 08:21:41.998751   35994 shipshape.go:327] Error from pull: exit status 1
[run -p=127.0.0.1:10007:10007 -v=/home/mernst/research/types/checker-framework:/shipshape-workspace -v=/tmp:/shipshape-output -e="START_SERVICE=true" -e="ANALYZERS=localhost:10005,localhost:10006" --name=shipping_container -d gcr.io/shipshape_releases/service:prod]E0523 08:21:42.108346   35994 shipshape.go:213] HTTP client did not become healthy: exit status 1

Unfortunately, I cannot interpret this output.

**Comment by emsod** [comment] 2015-05-26 20:54
Thanks for trying out ShipShape and sorry that you have to encounter this issue. We are working on a solution. Meanwhile, the issue may be caused by old docker containers. You could try to clean up previous docker containers using:

$ docker rm `docker ps -a -q`

**Comment by mernst** [comment] 2015-05-27 15:16
I see you have updated the installation instructions; thanks.
The problem seems to have been my docker installation rather than anything related to shipshape.
(I had just installed docker for the first time, and your command didn't work for me.)
In my case, rebooting after installing docker did the trick, a suggestion I found elsewhere on the Internet.

**Comment by emsod** [comment] 2015-05-28 19:18
Ok. Closing this issue. Please reopen if you see this problem again.

**Closed by emsod** 2015-05-28 19:18 UTC
